/* imports.c -- resolver table for the RVGL Android modules.
 *
 * GENERATED by tools/gen_imports.py. Do not hand-edit; change the generator
 * or add to EXPLICIT there, then regenerate. Run tools/verify_imports.py
 * afterwards -- it fails on any symbol this table does not cover.
 *
 * Modules loaded (order matches g_modules[] in main.c):
 *   libunistring.so      52 imports,   712 exports
 *   libmpg123.so         46 imports,   115 exports
 *   libsndfile.so        59 imports,    41 exports
 *   libopenal.so        126 imports,   168 exports
 *   libmain.so          331 imports,  3066 exports
 *
 * 420 distinct undefined symbols across all five:
 *
 *     58  resolved BY ANOTHER LOADED MODULE and therefore NOT listed here.
 *         so_resolve_symbol() checks this table first and loaded modules
 *         second, so an entry here would shadow the real implementation.
 *         This is what keeps al*, mpg123_*, sf_* and u8_* out of the table.
 *     93  SDL2 / SDL2_image  -> switch-sdl2, natively
 *    134  bionic shims       -> libc_shim.c
 *     55  hand-written       -> rv_sdl_stubs.c, compat_stubs.c, our log
 *      5  OpenSL ES          -> opensles.c
 *     75  newlib passthrough
 *
 *   362 entries below.
 *
 * These libraries are linked BIND_NOW, so every entry has to resolve before
 * the first call into a module. There is no lazy PLT to catch a mistake later:
 * a gap is a load-time abort, which is the behaviour we want, because it names
 * the symbol instead of faulting somewhere unrelated.
 */

#define _GNU_SOURCE

#include <stdlib.h>
#include <stdio.h>
#include <stdint.h>
#include <stdarg.h>
#include <string.h>
#include <strings.h>
#include <malloc.h>
#include <unistd.h>
#include <fcntl.h>
#include <ctype.h>
#include <math.h>
#include <pthread.h>
#include <time.h>
#include <wchar.h>
#include <wctype.h>
#include <errno.h>
#include <locale.h>
#include <setjmp.h>
#include <signal.h>
#include <sys/time.h>
#include <sys/stat.h>
#include <dirent.h>
#include <arpa/inet.h>

#include <SDL2/SDL.h>

#include "rv_image.h"   /* SDL2_image, or our stand-in -- see the header */

#include "so_util.h"
#include "imports.h"
#include "imports_helpers.h"
#include "rv_shim.h"
#include "libc_shim.h"
#include "compat_stubs.h"
#include "opensles.h"
#include "rv_log.h"
#include "rv_net.h"
#include "rv_input.h"
#include "rv_video.h"
#include "rv_events.h"
#include "rv_cursor.h"

extern const char *SDL_AndroidGetExternalStoragePath_stub(void);
extern SDL_bool SDL_AndroidRequestPermission_stub(const char *permission);

DynLibFunction dynlib_functions[] = {
  { "IMG_Init",                            (uintptr_t)&IMG_Init },
  { "IMG_Load_RW",                         (uintptr_t)&IMG_Load_RW },
  { "IMG_Quit",                            (uintptr_t)&IMG_Quit },
  { "IMG_SavePNG_RW",                      (uintptr_t)&IMG_SavePNG_RW },
  { "SDL_AndroidGetExternalStoragePath",   (uintptr_t)&SDL_AndroidGetExternalStoragePath_stub },
  { "SDL_AndroidRequestPermission",        (uintptr_t)&SDL_AndroidRequestPermission_stub },
  { "SDL_ConvertSurfaceFormat",            (uintptr_t)&SDL_ConvertSurfaceFormat },
  { "SDL_CreateMutex",                     (uintptr_t)&SDL_CreateMutex },
  { "SDL_CreateRGBSurface",                (uintptr_t)&SDL_CreateRGBSurface },
  { "SDL_CreateSemaphore",                 (uintptr_t)&SDL_CreateSemaphore },
  { "SDL_CreateSystemCursor",              (uintptr_t)&SDL_CreateSystemCursor },
  { "SDL_CreateThread",                    (uintptr_t)&SDL_CreateThread },
  { "SDL_CreateWindow",                    (uintptr_t)&rv_create_window },
  { "SDL_Delay",                           (uintptr_t)&SDL_Delay },
  { "SDL_DestroyMutex",                    (uintptr_t)&SDL_DestroyMutex },
  { "SDL_DestroySemaphore",                (uintptr_t)&SDL_DestroySemaphore },
  { "SDL_DestroyWindow",                   (uintptr_t)&SDL_DestroyWindow },
  { "SDL_DetachThread",                    (uintptr_t)&SDL_DetachThread },
  { "SDL_FreeSurface",                     (uintptr_t)&SDL_FreeSurface },
  { "SDL_GL_CreateContext",                (uintptr_t)&SDL_GL_CreateContext },
  { "SDL_GL_DeleteContext",                (uintptr_t)&SDL_GL_DeleteContext },
  { "SDL_GL_GetAttribute",                 (uintptr_t)&SDL_GL_GetAttribute },
  { "SDL_GL_GetDrawableSize",              (uintptr_t)&SDL_GL_GetDrawableSize },
  { "SDL_GL_GetProcAddress",               (uintptr_t)&SDL_GL_GetProcAddress },
  { "SDL_GL_MakeCurrent",                  (uintptr_t)&SDL_GL_MakeCurrent },
  { "SDL_GL_ResetAttributes",              (uintptr_t)&SDL_GL_ResetAttributes },
  { "SDL_GL_SetAttribute",                 (uintptr_t)&SDL_GL_SetAttribute },
  { "SDL_GL_SetSwapInterval",              (uintptr_t)&SDL_GL_SetSwapInterval },
  { "SDL_GL_SwapWindow",                   (uintptr_t)&rv_gl_swap_window },
  { "SDL_GameControllerAddMappingsFromRW", (uintptr_t)&SDL_GameControllerAddMappingsFromRW },
  { "SDL_GameControllerClose",             (uintptr_t)&SDL_GameControllerClose },
  { "SDL_GameControllerGetAxis",           (uintptr_t)&rv_pad_get_axis },
  { "SDL_GameControllerGetButton",         (uintptr_t)&rv_pad_get_button },
  { "SDL_GameControllerGetJoystick",       (uintptr_t)&SDL_GameControllerGetJoystick },
  { "SDL_GameControllerMappingForGUID",    (uintptr_t)&SDL_GameControllerMappingForGUID },
  { "SDL_GameControllerNameForIndex",      (uintptr_t)&SDL_GameControllerNameForIndex },
  { "SDL_GameControllerOpen",              (uintptr_t)&SDL_GameControllerOpen },
  { "SDL_GetBasePath",                     (uintptr_t)&SDL_GetBasePath },
  { "SDL_GetClipboardText",                (uintptr_t)&SDL_GetClipboardText },
  { "SDL_GetDesktopDisplayMode",           (uintptr_t)&rv_get_desktop_display_mode },
  { "SDL_GetDisplayMode",                  (uintptr_t)&rv_get_display_mode },
  { "SDL_GetError",                        (uintptr_t)&SDL_GetError },
  { "SDL_GetKeyFromScancode",              (uintptr_t)&SDL_GetKeyFromScancode },
  { "SDL_GetKeyboardState",                (uintptr_t)&rv_get_keyboard_state },
  { "SDL_GetModState",                     (uintptr_t)&SDL_GetModState },
  { "SDL_GetNumDisplayModes",              (uintptr_t)&SDL_GetNumDisplayModes },
  { "SDL_GetPerformanceCounter",           (uintptr_t)&SDL_GetPerformanceCounter },
  { "SDL_GetPerformanceFrequency",         (uintptr_t)&SDL_GetPerformanceFrequency },
  { "SDL_GetPlatform",                     (uintptr_t)&SDL_GetPlatform },
  { "SDL_GetPrefPath",                     (uintptr_t)&SDL_GetPrefPath },
  { "SDL_GetScancodeName",                 (uintptr_t)&SDL_GetScancodeName },
  { "SDL_GetVersion",                      (uintptr_t)&SDL_GetVersion },
  { "SDL_GetWindowSize",                   (uintptr_t)&SDL_GetWindowSize },
  { "SDL_HapticClose",                     (uintptr_t)&SDL_HapticClose },
  { "SDL_HapticDestroyEffect",             (uintptr_t)&SDL_HapticDestroyEffect },
  { "SDL_HapticIndex",                     (uintptr_t)&SDL_HapticIndex },
  { "SDL_HapticName",                      (uintptr_t)&SDL_HapticName },
  { "SDL_HapticNewEffect",                 (uintptr_t)&SDL_HapticNewEffect },
  { "SDL_HapticNumAxes",                   (uintptr_t)&SDL_HapticNumAxes },
  { "SDL_HapticNumEffects",                (uintptr_t)&SDL_HapticNumEffects },
  { "SDL_HapticOpenFromJoystick",          (uintptr_t)&SDL_HapticOpenFromJoystick },
  { "SDL_HapticQuery",                     (uintptr_t)&SDL_HapticQuery },
  { "SDL_HapticRunEffect",                 (uintptr_t)&SDL_HapticRunEffect },
  { "SDL_HapticSetAutocenter",             (uintptr_t)&SDL_HapticSetAutocenter },
  { "SDL_HapticSetGain",                   (uintptr_t)&SDL_HapticSetGain },
  { "SDL_HapticUpdateEffect",              (uintptr_t)&SDL_HapticUpdateEffect },
  { "SDL_HasClipboardText",                (uintptr_t)&SDL_HasClipboardText },
  { "SDL_Init",                            (uintptr_t)&SDL_Init },
  { "SDL_InitSubSystem",                   (uintptr_t)&SDL_InitSubSystem },
  { "SDL_IsGameController",                (uintptr_t)&SDL_IsGameController },
  { "SDL_IsTextInputActive",               (uintptr_t)&rv_is_text_input_active },
  { "SDL_JoystickClose",                   (uintptr_t)&SDL_JoystickClose },
  { "SDL_JoystickGetAxis",                 (uintptr_t)&rv_joy_get_axis },
  { "SDL_JoystickGetButton",               (uintptr_t)&rv_joy_get_button },
  { "SDL_JoystickGetDeviceGUID",           (uintptr_t)&SDL_JoystickGetDeviceGUID },
  { "SDL_JoystickGetGUIDString",           (uintptr_t)&SDL_JoystickGetGUIDString },
  { "SDL_JoystickIsHaptic",                (uintptr_t)&SDL_JoystickIsHaptic },
  { "SDL_JoystickNameForIndex",            (uintptr_t)&SDL_JoystickNameForIndex },
  { "SDL_JoystickNumAxes",                 (uintptr_t)&SDL_JoystickNumAxes },
  { "SDL_JoystickNumButtons",              (uintptr_t)&SDL_JoystickNumButtons },
  { "SDL_JoystickNumHats",                 (uintptr_t)&SDL_JoystickNumHats },
  { "SDL_JoystickOpen",                    (uintptr_t)&SDL_JoystickOpen },
  { "SDL_LockMutex",                       (uintptr_t)&SDL_LockMutex },
  { "SDL_NumJoysticks",                    (uintptr_t)&SDL_NumJoysticks },
  { "SDL_PollEvent",                       (uintptr_t)&rv_poll_event },
  { "SDL_Quit",                            (uintptr_t)&SDL_Quit },
  { "SDL_RWFromFile",                      (uintptr_t)&SDL_RWFromFile },
  { "SDL_RWclose",                         (uintptr_t)&SDL_RWclose },
  { "SDL_RWread",                          (uintptr_t)&SDL_RWread },
  { "SDL_SemPost",                         (uintptr_t)&SDL_SemPost },
  { "SDL_SemWait",                         (uintptr_t)&SDL_SemWait },
  { "SDL_SetClipboardText",                (uintptr_t)&SDL_SetClipboardText },
  { "SDL_SetCursor",                       (uintptr_t)&SDL_SetCursor },
  { "SDL_SetHint",                         (uintptr_t)&SDL_SetHint },
  { "SDL_SetRelativeMouseMode",            (uintptr_t)&SDL_SetRelativeMouseMode },
  { "SDL_SetWindowBrightness",             (uintptr_t)&SDL_SetWindowBrightness },
  { "SDL_SetWindowGammaRamp",              (uintptr_t)&SDL_SetWindowGammaRamp },
  { "SDL_SetWindowIcon",                   (uintptr_t)&SDL_SetWindowIcon },
  { "SDL_ShowMessageBox",                  (uintptr_t)&SDL_ShowMessageBox },
  { "SDL_ShowSimpleMessageBox",            (uintptr_t)&SDL_ShowSimpleMessageBox },
  { "SDL_StartTextInput",                  (uintptr_t)&rv_text_input_start },
  { "SDL_StopTextInput",                   (uintptr_t)&rv_text_input_stop },
  { "SDL_ThreadID",                        (uintptr_t)&SDL_ThreadID },
  { "SDL_TryLockMutex",                    (uintptr_t)&SDL_TryLockMutex },
  { "SDL_UnlockMutex",                     (uintptr_t)&SDL_UnlockMutex },
  { "SDL_WaitThread",                      (uintptr_t)&SDL_WaitThread },
  { "SDL_free",                            (uintptr_t)&SDL_free },
  { "SDL_setenv",                          (uintptr_t)&SDL_setenv },
  { "SL_IID_ANDROIDCONFIGURATION",         (uintptr_t)&SL_IID_ANDROIDCONFIGURATION },
  { "SL_IID_ANDROIDSIMPLEBUFFERQUEUE",     (uintptr_t)&SL_IID_ANDROIDSIMPLEBUFFERQUEUE },
  { "SL_IID_ENGINE",                       (uintptr_t)&SL_IID_ENGINE },
  { "SL_IID_PLAY",                         (uintptr_t)&SL_IID_PLAY },
  { "SL_IID_RECORD",                       (uintptr_t)&SL_IID_RECORD },
  { "__android_log_print",                 (uintptr_t)&rvnx_log_print },
  { "__ctype_get_mb_cur_max",              (uintptr_t)&__ctype_get_mb_cur_max_fake },
  { "__cxa_atexit",                        (uintptr_t)&__cxa_atexit_fake },
  { "__cxa_finalize",                      (uintptr_t)&__cxa_finalize_fake },
  { "__errno",                             (uintptr_t)&__errno },
  { "__google_potentially_blocking_region_begin", (uintptr_t)&rvnx_noop },
  { "__google_potentially_blocking_region_end", (uintptr_t)&rvnx_noop },
  { "__isfinitef",                         (uintptr_t)&rvnx_isfinitef },
  { "__isnanf",                            (uintptr_t)&rvnx_isnanf },
  { "__memcpy_chk",                        (uintptr_t)&__memcpy_chk_fake },
  { "__memset_chk",                        (uintptr_t)&__memset_chk_fake },
  { "__sF",                                (uintptr_t)&fake_sF },
  { "__stack_chk_fail",                    (uintptr_t)&__stack_chk_fail_fake },
  { "__stack_chk_guard",                   (uintptr_t)&rvnx_stack_chk_guard },
  { "__strlen_chk",                        (uintptr_t)&__strlen_chk_fake },
  { "__strrchr_chk",                       (uintptr_t)&__strrchr_chk_fake },
  { "_ctype_",                             (uintptr_t)&_ctype_ },  /* review */
  { "abort",                               (uintptr_t)&abort },
  { "accept",                              (uintptr_t)&rvn_accept },
  { "access",                              (uintptr_t)&access },
  { "acos",                                (uintptr_t)&acos },  /* review */
  { "acosf",                               (uintptr_t)&acosf },  /* review */
  { "asinf",                               (uintptr_t)&asinf },  /* review */
  { "atan2",                               (uintptr_t)&atan2 },  /* review */
  { "atan2f",                              (uintptr_t)&atan2f },  /* review */
  { "atof",                                (uintptr_t)&atof },  /* review */
  { "atoi",                                (uintptr_t)&atoi },  /* review */
  { "atol",                                (uintptr_t)&atol },  /* review */
  { "bind",                                (uintptr_t)&rvn_bind },
  { "btowc",                               (uintptr_t)&btowc },  /* review */
  { "calloc",                              (uintptr_t)&calloc },
  { "cbrt",                                (uintptr_t)&cbrt },  /* review */
  { "cbrtf",                               (uintptr_t)&cbrtf },  /* review */
  { "chdir",                               (uintptr_t)&chdir },  /* review */
  { "clearerr",                            (uintptr_t)&rvnx_clearerr_fn },
  { "clock_gettime",                       (uintptr_t)&clock_gettime_bionic },
  { "close",                               (uintptr_t)&rvn_close_hook },
  { "closedir",                            (uintptr_t)&closedir_fake },
  { "connect",                             (uintptr_t)&rvn_connect },
  { "cos",                                 (uintptr_t)&cos },
  { "cosf",                                (uintptr_t)&cosf },
  { "dl_iterate_phdr",                     (uintptr_t)&so_dl_iterate_phdr },
  { "expf",                                (uintptr_t)&expf },  /* review */
  { "fclose",                              (uintptr_t)&rv_profile_fclose },
  { "fcntl",                               (uintptr_t)&rvn_fcntl },
  { "fdopen",                              (uintptr_t)&fdopen_fake },
  { "feof",                                (uintptr_t)&feof_fake },
  { "ferror",                              (uintptr_t)&ferror_fake },
  { "fflush",                              (uintptr_t)&fflush_fake },
  { "fgetc",                               (uintptr_t)&fgetc_fake },
  { "fgetpos",                             (uintptr_t)&fgetpos },  /* review */
  { "fgets",                               (uintptr_t)&fgets_fake },
  { "fileno",                              (uintptr_t)&fileno_fake },
  { "fmod",                                (uintptr_t)&fmod },  /* review */
  { "fopen",                               (uintptr_t)&rv_profile_fopen },
  { "fprintf",                             (uintptr_t)&fprintf_fake },
  { "fputc",                               (uintptr_t)&fputc_fake },
  { "fputs",                               (uintptr_t)&fputs_fake },
  { "fread",                               (uintptr_t)&fread_fake },
  { "free",                                (uintptr_t)&free },
  { "freeaddrinfo",                        (uintptr_t)&rvn_freeaddrinfo },
  { "freopen",                             (uintptr_t)&freopen },  /* review */
  { "frexp",                               (uintptr_t)&frexp },  /* review */
  { "fscanf",                              (uintptr_t)&fscanf },  /* review */
  { "fseek",                               (uintptr_t)&fseek_fake },
  { "fseeko",                              (uintptr_t)&fseeko_fake },
  { "fsetpos",                             (uintptr_t)&fsetpos },  /* review */
  { "fstat",                               (uintptr_t)&fstat_fake },
  { "fsync",                               (uintptr_t)&pps_fsync },
  { "ftell",                               (uintptr_t)&ftell_fake },
  { "ftello",                              (uintptr_t)&ftello_fake },
  { "ftruncate",                           (uintptr_t)&pps_ftruncate },
  { "fwrite",                              (uintptr_t)&fwrite_fake },
  { "getaddrinfo",                         (uintptr_t)&rvn_getaddrinfo },
  { "getc",                                (uintptr_t)&getc_fake },
  { "getc_unlocked",                       (uintptr_t)&rvnx_getc_unlocked },
  { "getcwd",                              (uintptr_t)&getcwd_fake },
  { "getenv",                              (uintptr_t)&getenv_fake },
  { "getnameinfo",                         (uintptr_t)&rvn_getnameinfo },
  { "getsockname",                         (uintptr_t)&rvn_getsockname },
  { "getsockopt",                          (uintptr_t)&rvn_getsockopt },
  { "gettimeofday",                        (uintptr_t)&pps_gettimeofday },
  { "getwc",                               (uintptr_t)&getwc },  /* review */
  { "gmtime_r",                            (uintptr_t)&gmtime_r },  /* review */
  { "inet_ntop",                           (uintptr_t)&inet_ntop },  /* review */
  { "inet_pton",                           (uintptr_t)&inet_pton },  /* review */
  { "ioctl",                               (uintptr_t)&rvn_ioctl },
  { "isalnum",                             (uintptr_t)&isalnum_fn },
  { "isalpha",                             (uintptr_t)&isalpha_fn },
  { "isprint",                             (uintptr_t)&isprint_fn },
  { "isspace",                             (uintptr_t)&isspace_fn },
  { "iswcntrl",                            (uintptr_t)&iswcntrl_fn },
  { "iswctype",                            (uintptr_t)&iswctype },  /* review */
  { "link",                                (uintptr_t)&rvnx_link },
  { "listen",                              (uintptr_t)&rvn_listen },
  { "localtime",                           (uintptr_t)&pps_localtime },
  { "log",                                 (uintptr_t)&log },  /* review */
  { "log10f",                              (uintptr_t)&log10f },  /* review */
  { "log2f",                               (uintptr_t)&log2f },  /* review */
  { "logf",                                (uintptr_t)&logf },  /* review */
  { "lrint",                               (uintptr_t)&lrint },  /* review */
  { "lrintf",                              (uintptr_t)&lrintf },  /* review */
  { "lround",                              (uintptr_t)&lround },  /* review */
  { "lseek",                               (uintptr_t)&z_lseek },
  { "malloc",                              (uintptr_t)&malloc },
  { "mbrtowc",                             (uintptr_t)&mbrtowc },  /* review */
  { "mbsinit",                             (uintptr_t)&mbsinit },  /* review */
  { "memchr",                              (uintptr_t)&memchr },  /* review */
  { "memcmp",                              (uintptr_t)&memcmp },  /* review */
  { "memcpy",                              (uintptr_t)&memcpy },
  { "memmove",                             (uintptr_t)&memmove },
  { "memset",                              (uintptr_t)&memset },
  { "mkdir",                               (uintptr_t)&mkdir_fake },
  { "mmap",                                (uintptr_t)&mmap_fake },
  { "modf",                                (uintptr_t)&modf },  /* review */
  { "munmap",                              (uintptr_t)&munmap_fake },
  { "nanosleep",                           (uintptr_t)&pps_nanosleep },
  { "open",                                (uintptr_t)&open_fake },
  { "opendir",                             (uintptr_t)&pps_opendir },
  { "poll",                                (uintptr_t)&rvn_poll },
  { "posix_memalign",                      (uintptr_t)&posix_memalign_fake },
  { "pow",                                 (uintptr_t)&pow },  /* review */
  { "powf",                                (uintptr_t)&powf },
  { "printf",                              (uintptr_t)&pps_printf_discard },
  { "pthread_attr_destroy",                (uintptr_t)&pthread_attr_destroy },  /* review */
  { "pthread_attr_init",                   (uintptr_t)&pthread_attr_init },  /* review */
  { "pthread_attr_setstacksize",           (uintptr_t)&pthread_attr_setstacksize },  /* review */
  { "pthread_cond_broadcast",              (uintptr_t)&pthread_cond_broadcast_fake },
  { "pthread_cond_destroy",                (uintptr_t)&pthread_cond_destroy_fake },
  { "pthread_cond_init",                   (uintptr_t)&pthread_cond_init },  /* review */
  { "pthread_cond_signal",                 (uintptr_t)&pthread_cond_signal_fake },
  { "pthread_cond_wait",                   (uintptr_t)&pthread_cond_wait_fake },
  { "pthread_create",                      (uintptr_t)&pthread_create_fake },
  { "pthread_detach",                      (uintptr_t)&pthread_detach },  /* review */
  { "pthread_equal",                       (uintptr_t)&pthread_equal },  /* review */
  { "pthread_exit",                        (uintptr_t)&pthread_exit },  /* review */
  { "pthread_getspecific",                 (uintptr_t)&pthread_getspecific_fake },
  { "pthread_join",                        (uintptr_t)&pthread_join_fake },
  { "pthread_key_create",                  (uintptr_t)&pthread_key_create_fake },
  { "pthread_key_delete",                  (uintptr_t)&pthread_key_delete_fake },
  { "pthread_mutex_destroy",               (uintptr_t)&pthread_mutex_destroy_fake },
  { "pthread_mutex_init",                  (uintptr_t)&pthread_mutex_init_fake },
  { "pthread_mutex_lock",                  (uintptr_t)&pthread_mutex_lock_fake },
  { "pthread_mutex_trylock",               (uintptr_t)&pthread_mutex_trylock_fake },
  { "pthread_mutex_unlock",                (uintptr_t)&pthread_mutex_unlock_fake },
  { "pthread_mutexattr_destroy",           (uintptr_t)&ret0_i },
  { "pthread_mutexattr_init",              (uintptr_t)&pthread_mutexattr_init_fake },
  { "pthread_mutexattr_settype",           (uintptr_t)&pthread_mutexattr_settype_fake },
  { "pthread_once",                        (uintptr_t)&pthread_once_fake },
  { "pthread_self",                        (uintptr_t)&pthread_self },  /* review */
  { "pthread_setname_np",                  (uintptr_t)&rvnx_pthread_setname_np },
  { "pthread_setschedparam",               (uintptr_t)&rvnx_pthread_setschedparam },
  { "pthread_setspecific",                 (uintptr_t)&pthread_setspecific_fake },
  { "putc",                                (uintptr_t)&rvnx_putc },
  { "putchar",                             (uintptr_t)&rvnx_putchar },
  { "puts",                                (uintptr_t)&pps_puts_discard },
  { "putwc",                               (uintptr_t)&putwc },  /* review */
  { "qsort",                               (uintptr_t)&qsort },
  { "raise",                               (uintptr_t)&raise_stub },
  { "read",                                (uintptr_t)&read_fake },
  { "readdir",                             (uintptr_t)&readdir_fake },
  { "readlink",                            (uintptr_t)&pps_readlink },
  { "realloc",                             (uintptr_t)&realloc },
  { "recvmsg",                             (uintptr_t)&rvn_recvmsg },
  { "remove",                              (uintptr_t)&remove },
  { "rename",                              (uintptr_t)&rv_profile_rename },
  { "rewind",                              (uintptr_t)&rewind },  /* review */
  { "rmdir",                               (uintptr_t)&rmdir },
  { "sched_get_priority_min",              (uintptr_t)&sched_get_priority_min_fake },
  { "sched_yield",                         (uintptr_t)&sched_yield_fake },
  { "select",                              (uintptr_t)&rvn_select },
  { "sem_destroy",                         (uintptr_t)&sem_destroy_fake },
  { "sem_init",                            (uintptr_t)&sem_init_fake },
  { "sem_post",                            (uintptr_t)&sem_post_fake },
  { "sem_trywait",                         (uintptr_t)&sem_trywait_fake },
  { "sem_wait",                            (uintptr_t)&sem_wait_fake },
  { "sendmsg",                             (uintptr_t)&rvn_sendmsg },
  { "setlocale",                           (uintptr_t)&setlocale_bionic },
  { "setsockopt",                          (uintptr_t)&rvn_setsockopt },
  { "setvbuf",                             (uintptr_t)&setvbuf },
  { "shutdown",                            (uintptr_t)&rvn_shutdown },
  { "sigaction",                           (uintptr_t)&sigaction_stub },
  { "sigemptyset",                         (uintptr_t)&sigemptyset_stub },
  { "siglongjmp",                          (uintptr_t)&pps_siglongjmp },
  { "sigsetjmp",                           (uintptr_t)&pps_sigsetjmp },
  { "sin",                                 (uintptr_t)&sin },
  { "sinf",                                (uintptr_t)&sinf },
  { "sinhf",                               (uintptr_t)&sinhf },  /* review */
  { "slCreateEngine",                      (uintptr_t)&slCreateEngine },
  { "snprintf",                            (uintptr_t)&snprintf },
  { "socket",                              (uintptr_t)&rvn_socket },
  { "sprintf",                             (uintptr_t)&sprintf },  /* review */
  { "sqrt",                                (uintptr_t)&sqrt },  /* review */
  { "sqrtf",                               (uintptr_t)&sqrtf },  /* review */
  { "sscanf",                              (uintptr_t)&sscanf },  /* review */
  { "stat",                                (uintptr_t)&stat_fake },
  { "stpcpy",                              (uintptr_t)&stpcpy },  /* review */
  { "strcasecmp",                          (uintptr_t)&strcasecmp },  /* review */
  { "strcat",                              (uintptr_t)&strcat },
  { "strchr",                              (uintptr_t)&z_strchr },
  { "strcmp",                              (uintptr_t)&z_strcmp },
  { "strcoll",                             (uintptr_t)&strcoll },
  { "strcpy",                              (uintptr_t)&strcpy },
  { "strdup",                              (uintptr_t)&strdup },
  { "strerror",                            (uintptr_t)&strerror },  /* review */
  { "strftime",                            (uintptr_t)&strftime },
  { "strlen",                              (uintptr_t)&z_strlen },
  { "strncasecmp",                         (uintptr_t)&strncasecmp },  /* review */
  { "strncat",                             (uintptr_t)&strncat },
  { "strncmp",                             (uintptr_t)&z_strncmp },
  { "strncpy",                             (uintptr_t)&strncpy },
  { "strnlen",                             (uintptr_t)&strnlen },  /* review */
  { "strpbrk",                             (uintptr_t)&strpbrk },  /* review */
  { "strrchr",                             (uintptr_t)&z_strrchr },
  { "strstr",                              (uintptr_t)&z_strstr },
  { "strtod",                              (uintptr_t)&strtod },  /* review */
  { "strtof",                              (uintptr_t)&strtof },  /* review */
  { "strtol",                              (uintptr_t)&strtol },  /* review */
  { "strtold",                             (uintptr_t)&strtold },
  { "strtoul",                             (uintptr_t)&strtoul },  /* review */
  { "strxfrm",                             (uintptr_t)&strxfrm },
  { "syscall",                             (uintptr_t)&syscall_fake },
  { "sysconf",                             (uintptr_t)&sysconf_fake },
  { "time",                                (uintptr_t)&pps_time },
  { "tolower",                             (uintptr_t)&tolower_fn },
  { "toupper",                             (uintptr_t)&toupper_fn },
  { "towlower",                            (uintptr_t)&towlower_fn },
  { "towupper",                            (uintptr_t)&towupper_fn },
  { "ungetc",                              (uintptr_t)&ungetc_fake },
  { "ungetwc",                             (uintptr_t)&ungetwc },  /* review */
  { "uselocale",                           (uintptr_t)&uselocale_fake },
  { "vfprintf",                            (uintptr_t)&vfprintf_fake },
  { "vsnprintf",                           (uintptr_t)&vsnprintf },
  { "vsprintf",                            (uintptr_t)&vsprintf },
  { "wcrtomb",                             (uintptr_t)&wcrtomb },  /* review */
  { "wcscoll",                             (uintptr_t)&wcscoll },
  { "wcsftime",                            (uintptr_t)&wcsftime },  /* review */
  { "wcslen",                              (uintptr_t)&wcslen },  /* review */
  { "wcsxfrm",                             (uintptr_t)&wcsxfrm },
  { "wctob",                               (uintptr_t)&wctob },  /* review */
  { "wctype",                              (uintptr_t)&wctype },  /* review */
  { "wcwidth",                             (uintptr_t)&wcwidth },  /* review */
  { "wmemchr",                             (uintptr_t)&wmemchr },  /* review */
  { "wmemcmp",                             (uintptr_t)&wmemcmp },  /* review */
  { "wmemcpy",                             (uintptr_t)&wmemcpy },  /* review */
  { "wmemmove",                            (uintptr_t)&wmemmove },  /* review */
  { "wmemset",                             (uintptr_t)&wmemset },  /* review */
  { "write",                               (uintptr_t)&write_fake },
  { "writev",                              (uintptr_t)&rvnx_writev },

};

const size_t dynlib_numfunctions = sizeof(dynlib_functions) / sizeof(*dynlib_functions);

/* dlsym() backing for the loaded modules.
 *
 * Not merely for completeness: libopenal.so dlopen()s libOpenSLES.so and
 * resolves slCreateEngine plus five SL_IID_* ids by name. None of them appears
 * in any import table, so without this lookup audio initialises, finds
 * nothing, and plays silence with no error reported anywhere.
 */
uintptr_t dynlib_find_export(const char *name) {
  DynLibFunction *f = so_find_import(dynlib_functions, (int)dynlib_numfunctions, name);
  return f ? f->func : 0;
}
